# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'TMDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TMDB
  
  # Infrastructure
  pod 'PromiseKit', '~> 8'
  
  # Reactive frameworks
  pod 'RxSwift', '6.6.0'
  pod 'RxCocoa', '6.6.0'
  
  # Image Processing
  pod 'SDWebImage', '~> 5.0'
  
end
